# Generated by Django 3.2.9 on 2021-11-16 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dog',
            table='dogs',
        ),
    ]
